CREATE VIEW profile_name AS
SELECT PROFILE, RESOURCE_NAME, LIMIT
FROM DBA_PROFILES;

GRANT SELECT ON profile_name TO PUBLIC


CREATE VIEW profile_name AS
SELECT PROFILE, RESOURCE_NAME, LIMIT
FROM DBA_PROFILES;

SELECT *
FROM USER_ROLE_PRIVS
WHERE GRANTED_ROLE NOT IN (
    'CONNECT',
    'RESOURCE',
    'DBA',
    'EXP_FULL_DATABASE',
    'IMP_FULL_DATABASE',
    'LBAC_DBA',
    'ABSC'
)
ORDER BY GRANTED_ROLE;

SELECT * FROM profile_name

SELECT *
FROM DBA_PROFILES;


