const privilegeOptions = [
  "CREATE PROFILE",
  "ALTER PROFILE",
  "DROP PROFILE",
  "CREATE ROLE",
  "ALTER ANY ROLE",
  "DROP ANY ROLE",
  "GRANT ANY ROLE",
  "CREATE SESSION",
  "CREATE ANY TABLE",
  "ALTER ANY TABLE",
  "DROP ANY TABLE",
  "SELECT ANY TABLE",
  "DELETE ANY TABLE",
  "INSERT ANY TABLE",
  "UPDATE ANY TABLE",
  "CREATE TABLE",
  "CREATE USER",
  "ALTER USER",
  "DROP USER",
];

export default privilegeOptions;
